import DatosEquipo as Datos

"""

    RECORD CASA Y VISITA
    RATING OFENSIVO Y DEFENSIVO
    PUNTOS A FAVOR, EN CONTRA Y DIFERENCIAL
    RESULTADOS ULT. 5 ENCUENTROS
    RESULTADOS DE ANTERIORES ENCUENTROS CON EL RIVAL
    RESULTADOS ULT. 5 ENCUENTROS DEPENDIENDO C/V

"""

def ponderacion():

    

    return